### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by freepdk** [free-pdk/sdcc-pdk-code-examples#1]
Please add a LICENSE file to the project.

Something like MIT or similar would be highly appreciated.

**Comment by spth** [comment]
I have now added such a file.

Personally, I tend to prefer:
Something with nearly no requirements, usually CC0 for very simple code ( source that is just 1 file, fits on 1.5 screens).
A permissive license, usually zlib for medium examples.
Copyleft, preferably GPLv2+ for large examples.

For the ported Mini-C examples, I'll use their original MIT license.

Philipp
